### PR TITLE
#1150 | Federated Identity Server users incompatible with SPE Security

### PR DESCRIPTION
**Pull request by alan-null**

### CODE REVIEW

**Comment by wavveen** [comment]
@AdamNaj and @michaellwest We are having a issue with SPE in combination with Identity Server users, this PR would fix it. Do you think this PR can be merged anytime soon?

**Comment by moo2u2** [comment]
I'm working with a client who's using Azure AD and also needs this fix.  Unfortunately for business reasons it needs to come from the "official" releases, so it would be great if this PR could be merged!

**Comment by michaellwest** [comment]
Thank you for the feedback. If I made a beta package would you be able to test it?

**Comment by moo2u2** [comment]
Thanks! I'm happy to test it locally, and will speak to the client to see if they're happy to test it in a dev environment.

**Comment by wavveen** [comment]
@michaellwest We have a custom build of SPE 6.0, with this commit included, running on a prod environment for about 2 weeks now. No issues have been reported so far...

**Pull request merged**
