### PR TITLE
Added new commands for resetting fields + layouts.

### PR DESCRIPTION
**Pull request by Kasaku**
Added new commands Reset-ItemField and Reset-Layout. Can follow this with update to documentation.

### CODE REVIEW

**Comment by Kasaku** [comment]
No worries. If you want I'll add get the documentation done and add to the branch so it's included in this push.

**Comment by michaellwest** [comment]
That would be most helpful.

**Comment by Kasaku** [comment]
I've added the documentation. I generated the MAML and Markdown via the commands + scripts, but that ended up changing a whole load of the Markdown, many of which I hadn't touched the source files of. Thought this could be an environment issue, so am just pushing the .ps1 changes.

**Comment by michaellwest** [comment]
Alex, the ps1 will be just fine. We appreciate the effort. The rest will be
completed as part of the release steps in the next week or so.

**Pull request merged**
